[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.97"
attribute-derive = "0.10.3"
darling = "0.20.11"
jni = "0.21.1"
memoize = "0.5.1"
proc-macro-rules = "0.4.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
